### ISSUE TITLE
nuxi init doesn't work when selecting yarn

### ISSUE THREAD

**Issue by bmulholland** [nuxt/cli#273]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.6.0
- Nuxt Version:     -
- CLI Version:      3.9.1
- Nitro Version:    -
- Package Manager:  unknown
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Run `npx nuxi@latest init nuxt3`

Select any package manager

### Describe the bug

It crashes.

```
➤ YN0009: │ esbuild@npm:0.19.5 couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/00/dd4ntv795rx101d_l6wnvdyc0000gn/T/xfs-3e1909f1/build.log)
➤ YN0009: │ esbuild@npm:0.18.20 couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/00/dd4ntv795rx101d_l6wnvdyc0000gn/T/xfs-32f04585/build.log)
➤ YN0007: │ nuxt-app@workspace:. must be built because it never has been before or the last one failed
➤ YN0009: │ nuxt-app@workspace:. couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/00/dd4ntv795rx101d_l6wnvdyc0000gn/T/xfs-c9c03fa3/build.log)
```

logs are:

```
# This file contains the result of Yarn building a package (esbuild@npm:0.19.5)
# Script name: postinstall


node:internal/process/esm_loader:48
      internalBinding('errors').triggerUncaughtException(
                                ^
TypeError [Error]: [ERR_IMPORT_ASSERTION_TYPE_MISSING]: Module "file:///Users/bmulholland/dev/recital/nuxt3/.yarn/unplugged/esbuild-npm-0.19.5-107ce8536d/node_modules/esbuild/package.json" needs an import assertion of type "json"
    at load$1 (file:///Users/bmulholland/dev/recital/nuxt3/.pnp.loader.mjs:1457:17)
    at nextLoad (node:internal/modules/esm/hooks:832:28)
    at Hooks.load (node:internal/modules/esm/hooks:415:26)
    at handleMessage (node:internal/modules/esm/worker:168:24)
    at checkForMessages (node:internal/modules/esm/worker:117:28)
    at process.<anonymous> (node:internal/modules/esm/worker:136:5)
    at process.emit (node:events:514:28)
    at process.emit (/Users/bmulholland/dev/recital/nuxt3/.pnp.cjs:18020:25) {
  code: 'ERR_IMPORT_ASSERTION_TYPE_MISSING'
}

Node.js v20.6.0
```

**Comment by pi0** [comment]
Hi dear @bmulholland. I am trying locally with Node 18.16, latest `nuxi init` seems to be working fine:

<img width="886" alt="image" src="https://github.com/nuxt/cli/assets/5158436/97e92485-e985-4c51-a9b4-3996836123d3">


---

If you try with `nuxi init --no-install`, can you normally cd to the project and use `yarn install`?

> ➤ YN0009: │ esbuild@npm:0.19.5 couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/00/dd4ntv795rx101d_l6wnvdyc0000gn/T/xfs-3e1909f1/build.log)

This seems about env build issue. Do you have more logs?

**Comment by bmulholland** [comment]
Hey @pi0! Nice to hear from you, hope you're well :). Thanks for the `--no-install` idea; that helped me track it down better. The problem arises when using Yarn Berry (I'm on 4.0.1). When using Yarn Classic (`yarn set version classic`), the install works fine. But if the active version is modern yarn (`yarn set version stable`), then the yarn install fails.

Also, BTW, if you use --no-install, cd to the dir, and set the yarn version to stable, 2/3 error messages go away -- but there's still an issue with nuxt/kit. I'm not going to dive into that here, this is already long enough :)

So, some thoughts:

If the generated project only works for yarn classic, then ideally the package.json would enforce that. There's ways to set the yarn version in package.json, but actually it seems that's a feature only available in modern yarn, not yarn berry. Failing that, maybe the package manager prompt could be updated to say "yarn classic," not just "yarn"? It's not perfect but it's an improvement.

Alternatively, the generated project could be updated to work with the latest yarn. (Or maybe just add that as yet another option? :\). The advantage here (aside from being the latest!) is that this version of yarn has ways to set the correct version in the package.json. I think the binary is also usually included in the repo? I recognized that all of this is a bit of a PITA.

(Re: the logs, I included the contents of one of the build logs: that's the second log snipped in the original post.)

BTW -- I'd originally searched when I thought the issue was just "init fails," and didn't find any matches. After I'd resolved the Node issue, that narrowed it down to Yarn, and I see there's related issues for that. e.g. https://github.com/nuxt/cli/issues/217. That may have tips on how to fix the project to work on the latest.
