### ISSUE TITLE
Bug when installing modules

### ISSUE THREAD

**Issue by BenGoetemann** [nuxt/cli#438]
## Environment

Operating System: Darwin
Node Version: v18.16.0
Nuxt Version: 3.11.2
CLI Version: 3.11.1
Nitro Version: 2.9.6
Package Manager: yarn@1.22.21
Builder: -
User Config: devtools, app, css, runtimeConfig, modules, gtag, robots, site, sitemap, pinia, imports, tailwindcss, image, supabase, hooks, nitro, build
Runtime Modules: @pinia/nuxt@0.4.11, @nuxtjs/tailwindcss@6.12.0, @vueuse/nuxt@10.9.0, @nuxt/image@1.7.0, nuxt-swiper@1.2.2, @nuxtjs/supabase@1.2.2, nuxt-scheduler@0.1.9, @nuxtjs/sitemap@5.1.4, @nuxtjs/robots@3.0.0, @nuxt/content@2.12.1, nuxt-jsonld@2.0.8, nuxt-gtag@2.0.6
Build Modules: -

## Reproduction

Not possible

## Describe the bug

When installing a module with the npx nuxi@latest command like f.e.  `npx nuxi@latest module add gtag` command i get this error:

## Logs

```
ERROR  Command failed with exit code 1: corepack yarn add -D nuxt-gtag@latest                                          12:05:12

  at makeError (/Users/ben/.npm/_npx/b95349761371180e/node_modules/nuxi/dist/chunks/index3.mjs:1272:11)
  at handlePromise (/Users/ben/.npm/_npx/b95349761371180e/node_modules/nuxi/dist/chunks/index3.mjs:2510:26)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async executeCommand (/Users/ben/.npm/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.0f575f79.mjs:42:3)
  at async addDependency (/Users/ben/.npm/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.0f575f79.mjs:197:3)
  at async Object.setup (/Users/ben/.npm/_npx/b95349761371180e/node_modules/nuxi/dist/chunks/add2.mjs:26228:19)
  at async runCommand$1 (/Users/ben/.npm/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.6aad497e.mjs:1620:5)
  at async runCommand$1 (/Users/ben/.npm/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.6aad497e.mjs:1639:11)
  at async runCommand$1 (/Users/ben/.npm/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.6aad497e.mjs:1639:11)
  at async runMain$1 (/Users/ben/.npm/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.6aad497e.mjs:1777:7)
```

**Comment by loookashow** [comment]
Faced the same
