### ISSUE TITLE
Install module make 405 Method not Allowed issue

### ISSUE THREAD

**Issue by SwartZCoding** [nuxt/cli#510]
Hello everyone ! 

When i try to do the command : npx nuxi@latest module add @nuxtjs/tailwindcss, i recieve this error response. I have already try with others modules and i have the same issue.

Thanks in advance for all help i can recieve !

Environement : 
Node: v20.18.0
OS : Windows 11

` ERROR  [GET] "https://npm.pkg.github.com//@nuxtjs/tailwindcss/latest": 405 Method Not Allowed                09:05:15

  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async $fetch2 (/C:/Users/alter/Documents/extranet-web/node_modules/nuxi/dist/shared/nuxi.b88e7b0f.mjs:340:15)
  at async resolveModule (/C:/Users/alter/Documents/extranet-web/node_modules/nuxi/dist/chunks/add2.mjs:262:15)
  at async Object.setup (/C:/Users/alter/Documents/extranet-web/node_modules/nuxi/dist/chunks/add2.mjs:136:15)
  at async runCommand$1 (/C:/Users/alter/Documents/extranet-web/node_modules/nuxi/dist/shared/nuxi.3e201632.mjs:1620:5)
  at async runCommand$1 (/C:/Users/alter/Documents/extranet-web/node_modules/nuxi/dist/shared/nuxi.3e201632.mjs:1639:11)
  at async runCommand$1 (/C:/Users/alter/Documents/extranet-web/node_modules/nuxi/dist/shared/nuxi.3e201632.mjs:1639:11)
  at async runMain$1 (/C:/Users/alter/Documents/extranet-web/node_modules/nuxi/dist/shared/nuxi.3e201632.mjs:1777:7)`

**Comment by Tcheikovski** [comment]
Same error here on a fresh project

**Comment by manniL** [comment]
Do you have any custom registry set up?

**Comment by SwartZCoding** [comment]
> Do you have any custom registry set up?

no, personally, try with a fresh nodejs install & clean of my config

**Comment by abedio** [comment]
Same error here on a fresh project, with module @nuxtjs/i18n.

Environement :
Node : v20.18.0
OS : Debian GNU/Linux 12 (bookworm)

**Comment by Tcheikovski** [comment]
> Do you have any custom registry set up?

I do, but I already tried removing it, with the same result

**Comment by sgarciac** [comment]
Same problem here.

**Comment by naseefpv** [comment]
Same here, Tried to install Nuxt Scripts. got **"https://npm.pkg.github.com//@nuxt/scripts/latest": 405 Method Not Allowed**

**Comment by skarnl** [comment]
Glad i found this issue, I was worried the error was on my machine.
Just to give an additional +1 and maybe some helpful debug info:

```
❯ npx nuxi@latest module add i18n

ERROR  [GET] "https://npm.pkg.github.com//@nuxtjs/i18n/latest": 405 Method Not Allowed                 

  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async $fetch2 (node_modules/nuxi/dist/shared/nuxi.b88e7b0f.mjs:340:15)
  at async resolveModule (node_modules/nuxi/dist/chunks/add2.mjs:262:15)
  at async Object.setup (node_modules/nuxi/dist/chunks/add2.mjs:136:15)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.3e201632.mjs:1620:5)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.3e201632.mjs:1639:11)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.3e201632.mjs:1639:11)
  at async runMain$1 (node_modules/nuxi/dist/shared/nuxi.3e201632.mjs:1777:7)
```

( and the same for another module, `npx nuxi@latest module add cookie-control` )

**Comment by tkjaergaard** [comment]
Might be the same as #498

**Comment by manniL** [comment]
It is indeed the same @tkjaergaard. Closing the linked on in favor if this due to activity)

**Comment by tkjaergaard** [comment]
So the error happens here: https://github.com/nuxt/cli/blob/main/src/commands/module/add.ts#L276

It takes the first match with `/registry=(.*)/` in the resolved .npmrc file. In my case it was `~/.npmrc`

The issue was introduced in #470.

It sees that the regex is not considering the "scope" defined prior to `registry=` e.g.: `@myscope:registry=https://npm.pkg.github.com/`

So even though you have specified that the registry should only work for a specific scope,  `getRegistryFromFile` takes the first match and use it as the registry.


Maybe an additional scope check in `getRegistryFromFile` should be implemented?

**Comment by tkjaergaard** [comment]
Gave it my best shot in #519
