### ISSUE TITLE
running info command on a workspace directory can throw error

### ISSUE THREAD

**Issue by danielroe** [nuxt/cli#84]
Running `nuxi info` on a directory without a lockfile can throw an error if it is part of a corepack-enabled workspace

```
❯ bunx nuxi-ng@latest info playground

 ERROR  Command failed: yarn --version                                                        08:58:47

  at checkExecSyncError (node:child_process:885:11)
  at execSync (node:child_process:957:15)
  at getPackageManagerVersion (node_modules/.pnpm/file+..+nuxt+cli+nuxi-ng-0.2.0.tgz/node_modules/nuxi-ng/dist/shared/nuxi-ng.0fad3f53.mjs:23:10)
  at Object.run (node_modules/.pnpm/file+..+nuxt+cli+nuxi-ng-0.2.0.tgz/node_modules/nuxi-ng/dist/chunks/info.mjs:64:31)
  at runCommand$1 (node_modules/.pnpm/file+..+nuxt+cli+nuxi-ng-0.2.0.tgz/node_modules/nuxi-ng/dist/shared/nuxi-ng.9b055368.mjs:1644:15)
  at async runCommand$1 (node_modules/.pnpm/file+..+nuxt+cli+nuxi-ng-0.2.0.tgz/node_modules/nuxi-ng/dist/shared/nuxi-ng.9b055368.mjs:1638:7)
  at async runMain$1 (node_modules/.pnpm/file+..+nuxt+cli+nuxi-ng-0.2.0.tgz/node_modules/nuxi-ng/dist/shared/nuxi-ng.9b055368.mjs:1756:7)
```

**Comment by danielroe** [comment]
Not a bug.
